version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 339494983275.dkr.ecr.ap-southeast-2.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
      - docker build -t $ImageName .

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker tag $ImageName:latest 339494983275.dkr.ecr.ap-southeast-2.amazonaws.com/$ImageName:latest
      - docker push 339494983275.dkr.ecr.ap-southeast-2.amazonaws.com/$ImageName:latest

cache:
  paths:
    - /root/.m2/**/*